== Python

Python est un *langage de programmation*.

Il fait maintenant partie de l'enseignement des mathématiques en France.

Il est utilisé dans le calcul scientifique, l'intelligence artificielle, le web, et beaucoup d'autres choses.

=== Interpréteur interactif

L'interpréteur interactif permet de taper des commandes Python, une à une et d'afficher le résultat (et les erreurs quand on se trompe).
Il est possible de remonter dans l'historique, pour reprendre une ligne précédante, sans avoir à tout retaper.

L'interpréteur interactif de Python est disponible sur Internet sans avoir besoin d'installer quoi que ce soit : link:https://pyodide.org/en/stable/console.html[Pyodide interactif].

=== Interpréteur

L'interpréteur Python va lire des fichiers contenant du code Python.

Ces fichiers seront édités avec un éditeur de texte.

Des éditeurs en ligne, combinant un éditeur de texte et un interpréteur, permettent d'éditer du code, confortablement, sans rien devoir installer.
link:https://www.mycompiler.io/fr/new/python[MyCompiler] est l'un d'eux.

[TIP]
.ハッキング Hakkingu
--

Python est un langage *interprété*, *faiblement typé*.

Python a un link:https://docs.python.org/fr/3.13/tutorial/interpreter.html[tutorial officiel].

La plupart des interpréteurs intéractifs fournissent de la complétion.
La touche `->|` propose de compléter le début de mot que l'on a tapé.

Il existe des interpréteurs interactifs plus pratiques que celui par défaut, comme link:https://ipython.org/[iPython].

Pyodide, qui permet de lancer du Python sur Internet, tourne dans le navigateur web, avec *web assembly*, sans solliciter le serveur web.

--
