== Types

Python utilise des valeurs de différents types.

=== Nombres

==== int : Entier

```
>>> 1+2
3
>>> 1-2
-1
```

==== float : Nombre réel

```
>>> 1/2
0.5
```

Python utilise la notation anglaise, avec un point comme séparateur et non une virgule.

Python transforme un `int` en `float` lorsque c'est nécessaire.

==== Opérateurs

Python fournit tous les opérateurs de base et gère les priorités.
Il est possible de mettre plusieurs espaces avant/après les opérateurs.

```
>>> 1+2*3
7
>>> (1+2)*3
9
>>> 3*7
21
>>> # ** : puissance
>>> 3**2
9
```

==== bool : Booléen

`True` pour vrai, `False` pour faux.

Les `bool` ont leurs propres opérateurs :

```
>>> True or False
True
>>> True and False
False
>>> not False
True
```

Les comparateurs permettent de créer un booléen comparant deux valeurs : une *clause*.

```
>>> 1 == 2
False
>>> 1 != 2
True
>>> 1 > 2
False
>>> 1 <= 2
True
```

Pour distinguer le `=` qui sert à assigner une valeur, une comparaison d'égalité va utiliser le *double égal* `==`.
Par convention, l'opérateur pour "différent" est *point d'exclamation égal* `!=`.

=== Collections

Les collections permettent de regrouper des valeurs.

Les collections ont une taille :

```
>>> len("oui")
3
```

==== str : Chaine de caractères

Une `str` utilise comme séparateur des guillemets simples `'` ou doubles `"`.
Il est possible d'échapper un séparateur avec un `\`, si l'on utilise des `'` et des `"`

```
>>> "J'aime les carottes"
"J'aime les carottes"
>>> 'J\'aime les carottes'
"J'aime les carottes"
```

Quelques opérations sont utilisables avec les `str` :

```
>>> 3 * "po"
'popopo'
>>> "Allo " + 'quoi'
'Allo quoi'
```

==== list : Liste

Une `list` est ordonnée, accepte le mélange de types et quelques opérateurs.
Les éléments d'une liste sont accessibles par leurs positions.
Attention, en informatique, on aime bien compter à partir de 0, et non de 1.
Dans l'exemple, l'élément 1 désigne le deuxième dans la liste.

```
>>> [1, "hop", 2.5]
[1, 'hop', 2.5]
>>> 3 * [1, 2]
[1, 2, 1, 2, 1, 2]
>>> ["il", "fait"] + ["beau"]
['il', 'fait', 'beau']
>>> ["pomme", "poire", "scoubidou"][1]
'poire'
```

==== tuple : Tuple

Un `tuple` est une liste immuable (que l'on ne peut pas modifier).
Les tuples sont essentiellement utilisés par les fonctions quand elles renvoient plusieurs valeurs.

==== dict : dictionnaire

Dans une liste, les éléments sont accessibles par leur rang, dans un dictionnaire, par une clef (de n'importe quel type).

```
>>> { "un": 1, "deux": 2}
{'un': 1, 'deux': 2}
>>> { "un": 1, "deux": 2}["deux"]
2
```

[TIP]
.ハッキング Hakkingu
--

Les `str` utilisent UTF8, ce qui permet l'utilisation des smileys : `"J'adore 🐍"`.

Les listes disposent d'une syntaxe plus souple pour favoriser la lisibilité : il est possible d'utiliser plusieurs lignes et d'avoir une virgule en trop à la fin de la liste (pour faciliter le copier/coller).

```
>>> [1,
... 2,
... ]
[1, 2]
```

Une `str` est une `list` spécialisée dans les lettres.

Des collections de collections sont possibles.

Bien plus de link:https://docs.python.org/fr/3.13/library/stdtypes.html[types Python existent].

--
